version: '3.8'
services:
  db:
    container_name: crawler-db
    image: postgres:12.0
    volumes:
      - crawler-data:/var/lib/postgresql/data
      - ./docker/postgresql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: pg

  app:
    container_name: crawler-app
    build: ./docker/php-apache
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./:/var/www/html
    environment:
      DATABASE_URL: "postgres://pg:pg@db/pg"
      DATABASE_TEST_URL: "postgres://pg:pg@db/test"

volumes:
  crawler-data:
    driver: local
